# Generated by Django 6.0.5 on 2026-05-28 20:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        ("ingestion", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmissionFactor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("activity_type", models.CharField(max_length=100)),
                ("fuel_or_category", models.CharField(max_length=100)),
                ("unit", models.CharField(max_length=50)),
                (
                    "factor_kg_co2e",
                    models.DecimalField(decimal_places=6, max_digits=12),
                ),
                ("source_reference", models.CharField(max_length=255)),
                ("year", models.IntegerField(default=2024)),
            ],
            options={
                "unique_together": {
                    ("activity_type", "fuel_or_category", "unit", "year")
                },
            },
        ),
        migrations.CreateModel(
            name="UnitConversion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("from_unit", models.CharField(max_length=50)),
                ("to_unit", models.CharField(max_length=50)),
                ("multiplier", models.DecimalField(decimal_places=8, max_digits=15)),
            ],
            options={
                "unique_together": {("from_unit", "to_unit")},
            },
        ),
        migrations.CreateModel(
            name="EmissionRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "scope",
                    models.IntegerField(
                        choices=[(1, "Scope 1"), (2, "Scope 2"), (3, "Scope 3")]
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("stationary_combustion", "Stationary Combustion"),
                            ("mobile_combustion", "Mobile Combustion"),
                            ("purchased_electricity", "Purchased Electricity"),
                            ("purchased_goods", "Purchased Goods & Services"),
                            ("business_travel_air", "Business Travel - Air"),
                            ("business_travel_hotel", "Business Travel - Hotel"),
                            (
                                "business_travel_ground",
                                "Business Travel - Ground Transport",
                            ),
                        ],
                        max_length=50,
                    ),
                ),
                ("activity_description", models.CharField(blank=True, max_length=500)),
                (
                    "original_quantity",
                    models.DecimalField(decimal_places=4, max_digits=15),
                ),
                ("original_unit", models.CharField(max_length=50)),
                (
                    "normalized_quantity",
                    models.DecimalField(decimal_places=4, max_digits=15),
                ),
                ("normalized_unit", models.CharField(max_length=50)),
                (
                    "emission_factor_used",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=12, null=True
                    ),
                ),
                (
                    "co2e_kg",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=15, null=True
                    ),
                ),
                ("period_start", models.DateField(blank=True, null=True)),
                ("period_end", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("validated", "Validated"),
                            ("suspicious", "Suspicious"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("locked", "Locked"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("is_suspicious", models.BooleanField(default=False)),
                ("suspicion_reasons", models.JSONField(blank=True, default=list)),
                ("reviewed_by", models.CharField(blank=True, max_length=150)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "raw_record",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="emission_record",
                        to="ingestion.rawrecord",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="emission_records",
                        to="ingestion.datasource",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="emission_records",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["tenant", "status"],
                        name="emissions_e_tenant__5a7e62_idx",
                    ),
                    models.Index(
                        fields=["tenant", "scope"],
                        name="emissions_e_tenant__80b9f6_idx",
                    ),
                    models.Index(
                        fields=["source"], name="emissions_e_source__54d801_idx"
                    ),
                ],
            },
        ),
    ]
